name: GitHub Pages

on: 
  push:
    banches:
      - main
  pull_request:

jobs:
  copy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: "copy from public to docs"
        run: cp -r ./public ./docs
